# Generated by Django 5.0.6 on 2026-09-03 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailconnection',
            name='job_search_started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GmailJobEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('thread_id', models.CharField(max_length=255)),
                ('sender', models.TextField(blank=True)),
                ('subject', models.TextField(blank=True)),
                ('email_date', models.TextField(blank=True)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gmail_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_emails', to='gmail.gmailconnection')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gmailjobemail',
            constraint=models.UniqueConstraint(fields=('gmail_connection', 'message_id'), name='unique_gmail_message_per_connection'),
        ),
    ]
