# Generated by Django 5.0.6 on 2026-09-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0002_gmailconnection_job_search_started_on_gmailjobemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailconnection',
            name='historical_next_page_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='historical_sync_completed',
            field=models.BooleanField(default=False),
        ),
    ]
