# Generated by Django 5.0.6 on 2026-09-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0003_gmailconnection_historical_next_page_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailconnection',
            name='last_history_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
