# Generated by Django 5.0.6 on 2026-09-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0004_gmailconnection_last_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailconnection',
            name='incremental_next_page_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='pending_history_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
