# Generated by Django 5.0.6 on 2026-09-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0005_gmailconnection_incremental_next_page_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailjobemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gmailjobemail',
            name='thread_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
