# Generated by Django 5.0.6 on 2026-09-12 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0006_alter_gmailjobemail_created_at_and_more'),
        ('jobs', '0003_remove_jobapplication_unique_gmail_thread_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailjobemail',
            name='body_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gmailjobemail',
            name='job_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_emails', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='gmailjobemail',
            name='snippet',
            field=models.TextField(blank=True, default=''),
        ),
    ]
