# Generated by Django 5.0.6 on 2026-09-03 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role_title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='applied', max_length=30)),
                ('source', models.CharField(choices=[('gmail', 'Gmail'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('gmail_thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_gmail_message_id', models.CharField(blank=True, max_length=255)),
                ('last_email_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_email_at', '-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('user', 'gmail_thread_id'), name='unique_gmail_thread_per_user'),
        ),
    ]
