# Generated by Django 5.0.6 on 2025-12-30 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='max_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='stage',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('ASSESSMENT', 'Assessment'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer')], db_index=True, default='APPLIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='verdict',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('GHOSTED', 'Ghosted')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stagehistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', '-created_at'], name='jobs_jobapp_user_id_898a69_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'stage'], name='jobs_jobapp_user_id_88e4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'verdict'], name='jobs_jobapp_user_id_229b79_idx'),
        ),
        migrations.AddIndex(
            model_name='stagehistory',
            index=models.Index(fields=['job', '-changed_at'], name='jobs_stageh_job_id_8951ae_idx'),
        ),
    ]
