# Generated by Django 5.0.6 on 2026-09-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='last_email_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
